# Generated by Django 5.2.11 on 2026-02-04 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('NONE', '-'), ('FERIE', 'Ferie'), ('SYG', 'Syg'), ('MOEDT', 'Mødt'), ('GAAET', 'Gået')], default='NONE', max_length=10)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['callsign'],
            },
        ),
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_status', models.CharField(choices=[('NONE', '-'), ('FERIE', 'Ferie'), ('SYG', 'Syg'), ('MOEDT', 'Mødt'), ('GAAET', 'Gået')], max_length=10)),
                ('new_status', models.CharField(choices=[('NONE', '-'), ('FERIE', 'Ferie'), ('SYG', 'Syg'), ('MOEDT', 'Mødt'), ('GAAET', 'Gået')], max_length=10)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller_status_logs', to=settings.AUTH_USER_MODEL)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='vagt.controller')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
